local function openFile()
    local file = assert(io.open('./var/signo.txt'))
    local tbl = {}
    local arr = {}

    -- remove duplicate
    for line in file:lines() do
        local errno = line:match('^SIG[A-Z0-9]+$')
        if not errno then
            error('invalid line: ' .. line)
        end
        tbl[errno] = true;
    end

    for errno in pairs(tbl) do
        arr[#arr + 1] = errno
    end
    table.sort(arr)

    return arr
end

local function codeGen(arr)
    local fmtConstants = [[
#ifdef %s
    lauxh_pushint2tbl(L, "%s", %s);
#endif
]];
    local list = {
        string.format([[
/**
 * src/gen_signals.h
 * this file generated by signogen.lua
 * %s
 */
]], os.date('%c')),
    }
    for i, v in ipairs(arr) do
        list[i + 1] = fmtConstants:format(v, v, v)
    end
    return list
end

local function output(tbl)
    local file = assert(io.open('./src/gen_signals.h', 'w+'))
    file:write(table.concat(tbl, '\n'))
    file:close()
end

output(codeGen(openFile()))
