/**
 * src/gen_signals.h
 * this file generated by signogen.lua
 * Sat Oct 14 08:50:00 2023
 */

#ifdef SIGABRT
    lauxh_pushint2tbl(L, "SIGABRT", SIGABRT);
#endif

#ifdef SIGALRM
    lauxh_pushint2tbl(L, "SIGALRM", SIGALRM);
#endif

#ifdef SIGBUS
    lauxh_pushint2tbl(L, "SIGBUS", SIGBUS);
#endif

#ifdef SIGCHLD
    lauxh_pushint2tbl(L, "SIGCHLD", SIGCHLD);
#endif

#ifdef SIGCONT
    lauxh_pushint2tbl(L, "SIGCONT", SIGCONT);
#endif

#ifdef SIGEMT
    lauxh_pushint2tbl(L, "SIGEMT", SIGEMT);
#endif

#ifdef SIGFPE
    lauxh_pushint2tbl(L, "SIGFPE", SIGFPE);
#endif

#ifdef SIGHUP
    lauxh_pushint2tbl(L, "SIGHUP", SIGHUP);
#endif

#ifdef SIGILL
    lauxh_pushint2tbl(L, "SIGILL", SIGILL);
#endif

#ifdef SIGINFO
    lauxh_pushint2tbl(L, "SIGINFO", SIGINFO);
#endif

#ifdef SIGINT
    lauxh_pushint2tbl(L, "SIGINT", SIGINT);
#endif

#ifdef SIGIO
    lauxh_pushint2tbl(L, "SIGIO", SIGIO);
#endif

#ifdef SIGKILL
    lauxh_pushint2tbl(L, "SIGKILL", SIGKILL);
#endif

#ifdef SIGPIPE
    lauxh_pushint2tbl(L, "SIGPIPE", SIGPIPE);
#endif

#ifdef SIGPROF
    lauxh_pushint2tbl(L, "SIGPROF", SIGPROF);
#endif

#ifdef SIGPWR
    lauxh_pushint2tbl(L, "SIGPWR", SIGPWR);
#endif

#ifdef SIGQUIT
    lauxh_pushint2tbl(L, "SIGQUIT", SIGQUIT);
#endif

#ifdef SIGRTMAX
    lauxh_pushint2tbl(L, "SIGRTMAX", SIGRTMAX);
#endif

#ifdef SIGRTMIN
    lauxh_pushint2tbl(L, "SIGRTMIN", SIGRTMIN);
#endif

#ifdef SIGSEGV
    lauxh_pushint2tbl(L, "SIGSEGV", SIGSEGV);
#endif

#ifdef SIGSTKFLT
    lauxh_pushint2tbl(L, "SIGSTKFLT", SIGSTKFLT);
#endif

#ifdef SIGSTOP
    lauxh_pushint2tbl(L, "SIGSTOP", SIGSTOP);
#endif

#ifdef SIGSYS
    lauxh_pushint2tbl(L, "SIGSYS", SIGSYS);
#endif

#ifdef SIGTERM
    lauxh_pushint2tbl(L, "SIGTERM", SIGTERM);
#endif

#ifdef SIGTRAP
    lauxh_pushint2tbl(L, "SIGTRAP", SIGTRAP);
#endif

#ifdef SIGTSTP
    lauxh_pushint2tbl(L, "SIGTSTP", SIGTSTP);
#endif

#ifdef SIGTTIN
    lauxh_pushint2tbl(L, "SIGTTIN", SIGTTIN);
#endif

#ifdef SIGTTOU
    lauxh_pushint2tbl(L, "SIGTTOU", SIGTTOU);
#endif

#ifdef SIGURG
    lauxh_pushint2tbl(L, "SIGURG", SIGURG);
#endif

#ifdef SIGUSR1
    lauxh_pushint2tbl(L, "SIGUSR1", SIGUSR1);
#endif

#ifdef SIGUSR2
    lauxh_pushint2tbl(L, "SIGUSR2", SIGUSR2);
#endif

#ifdef SIGVTALRM
    lauxh_pushint2tbl(L, "SIGVTALRM", SIGVTALRM);
#endif

#ifdef SIGWINCH
    lauxh_pushint2tbl(L, "SIGWINCH", SIGWINCH);
#endif

#ifdef SIGXCPU
    lauxh_pushint2tbl(L, "SIGXCPU", SIGXCPU);
#endif

#ifdef SIGXFSZ
    lauxh_pushint2tbl(L, "SIGXFSZ", SIGXFSZ);
#endif
